query getCurrentAuthenticatedUser{
    getCurrentAuthenticatedUser{
        dailyLimit
        foods{
            calorieValue
            dateTaken
            id
            name
            price
        }
        id
        password
        registrationNumber
        role
        userName
    }
}